"""merge heads

Revision ID: f734849d1e62
Revises: 7c85a2ef810b, [autogenerated_id]
Create Date: 2025-03-05 16:39:11.659628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f734849d1e62'
down_revision = ('7c85a2ef810b', '[autogenerated_id]')  # tuple of revision IDs being merged
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
